name: Lint, Format, and Type Check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  checks: write
  contents: write

jobs:
  CI-Lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1

    - name: Setup Pipenv
      run: |
        pip install pipenv
        pipenv install --ignore-pipfile --dev --system

    - name: Lint
      uses: wearerequired/lint-action@v1
      with:
        auto_fix: true
        black: true
        black_args: --exclude tests
        flake8: true

    - name: Type Checking
      uses: jakebailey/pyright-action@v1
      with:
        working-directory: sheets